version: '3.7'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: plant-postgres
    environment:
      POSTGRES_DB: plant-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  # Plant Backend
  plant-backend:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/plant-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass
      JWT_SECRET: ${JWT_SECRET}  # Make sure this is set from .env
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env  # This will ensure the .env file is loaded for this service

volumes:
  postgres-data:
