services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: plant-postgres
    environment:
      POSTGRES_DB: plant-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  plant-backend:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/plant-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres-data: